# Generated by Django 6.0.5 on 2026-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='habilidades_pessoais',
            field=models.TextField(blank=True, help_text='Habilidades do membro separadas por vírgula (ex: Tocar Bateria, Edição de Vídeo)'),
        ),
    ]
