# Generated by Django 6.0.5 on 2026-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membro_habilidades_pessoais'),
        ('gestao_membros', '0005_habilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='habilidades_pessoais',
        ),
        migrations.AddField(
            model_name='membro',
            name='habilidades',
            field=models.ManyToManyField(blank=True, related_name='membros', to='gestao_membros.habilidade'),
        ),
    ]
