# Generated by Django 6.0.5 on 2026-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracaosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Ex: CULTOS AOS DOMINGOS 09:30 E 19:30', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Notícia Plantão (Letreiro)',
                'verbose_name_plural': 'Notícias Plantão (Letreiro)',
                'ordering': ['ordem'],
            },
        ),
    ]
