# Generated by Django 6.0.5 on 2026-05-27 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_noticiaticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='igreja_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='igreja_nome',
            field=models.CharField(default='PV Enseada', help_text='Nome da Igreja no cabeçalho e login', max_length=150),
        ),
        migrations.AlterField(
            model_name='membro',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
