# Generated by Django 6.0.5 on 2026-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracaosistema_igreja_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='anotacoes_lideranca',
            field=models.TextField(blank=True, help_text='Anotações privadas da liderança sobre o membro'),
        ),
        migrations.AddField(
            model_name='membro',
            name='dias_folga',
            field=models.CharField(blank=True, help_text='Dias de folga separados por vírgula (0=Seg, 6=Dom)', max_length=50),
        ),
        migrations.AddField(
            model_name='membro',
            name='dias_trabalho',
            field=models.CharField(blank=True, help_text='Dias trabalhados separados por vírgula (0=Seg, 6=Dom)', max_length=50),
        ),
        migrations.AddField(
            model_name='membro',
            name='horario_trabalho_fim',
            field=models.TimeField(blank=True, help_text='Fim do expediente de trabalho ou estudo', null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='horario_trabalho_inicio',
            field=models.TimeField(blank=True, help_text='Início do expediente de trabalho ou estudo', null=True),
        ),
    ]
