# Generated by Django 6.0.5 on 2026-05-27 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_membro_anotacoes_lideranca_membro_dias_folga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='lider_global_escalas',
            field=models.ForeignKey(blank=True, help_text='Pessoa responsável pela gestão global de todas as escalas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_global_de_escalas', to=settings.AUTH_USER_MODEL),
        ),
    ]
