# Generated by Django 6.0.5 on 2026-05-28 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracaosistema_lider_global_escalas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da Instituição', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço Completo para Rodapés e Recibos', null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone pequeno exibido na aba do navegador', null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome Fantasia (Usado nos Títulos/Abas do navegador)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='igreja_nome',
            field=models.CharField(default='PV Enseada', help_text='Nome Real ou Razão Social (Usado no topo e painéis)', max_length=150),
        ),
    ]
