# Generated by Django 6.0.5 on 2026-05-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configuracaosistema_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='envios_email_ativos',
            field=models.BooleanField(default=True, help_text='Master switch. Se falso, nenhum email será disparado (modo silencioso/manutenção).'),
        ),
    ]
