# Generated by Django 6.0.5 on 2026-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuracaosistema_envios_email_ativos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_acao', models.CharField(help_text='Ex: escala_publicada, bem_vindo, termo_emprestimo', max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('pdf', 'PDF / Relatório')], default='email', max_length=20)),
                ('assunto_padrao', models.CharField(blank=True, help_text='Usado apenas se for E-mail', max_length=255, null=True)),
                ('html_content', models.TextField(blank=True)),
                ('css_content', models.TextField(blank=True)),
                ('components_json', models.JSONField(blank=True, help_text='Estrutura de blocos do GrapesJS', null=True)),
                ('variaveis_disponiveis', models.TextField(blank=True, help_text='Ex: {{ nome }}, {{ departamento.logo.url }}')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Dinâmico',
                'verbose_name_plural': 'Templates Dinâmicos',
            },
        ),
    ]
