# Generated by Django 6.0.5 on 2026-05-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_templatedocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='cidade_origem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='isp_origem',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
