# Generated by Django 6.0.5 on 2026-06-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_logauditoria_cidade_origem_logauditoria_isp_origem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('icone_svg', models.TextField(blank=True, help_text='Código SVG do ícone')),
                ('ordem', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Link Rápido',
                'verbose_name_plural': 'Links Rápidos',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='membro',
            name='alergias',
            field=models.TextField(blank=True, help_text='Alergias ou restrições alimentares/médicas'),
        ),
        migrations.AddField(
            model_name='membro',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='contato_emergencia',
            field=models.CharField(blank=True, help_text='Nome e telefone para emergências', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='data_batismo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='igreja_anterior',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='membro_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='redes_sociais',
            field=models.CharField(blank=True, help_text='Ex: @instagram', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='status_conta',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado'), ('transferido', 'Transferido'), ('falecido', 'Falecido')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='membro',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('XXG', 'XXG')], max_length=10, null=True),
        ),
    ]
