# Generated by Django 6.0.5 on 2026-06-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_linkrapido_membro_alergias_membro_bairro_membro_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='pin_pdv',
            field=models.CharField(blank=True, help_text='PIN de 4 dígitos para acesso rápido ao Caixa PDV', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='nivel_hierarquico',
            field=models.CharField(choices=[('super_admin', 'Super-admin'), ('pastor_regente', 'Pastor Regente'), ('pastor', 'Pastor'), ('missionario', 'Missionário'), ('lider', 'Líder'), ('sub_lider', 'Sub-líder'), ('membro_voluntario', 'Membro Voluntário')], default='membro_voluntario', max_length=30),
        ),
    ]
