# Generated by Django 6.0.5 on 2026-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_membro_pin_pdv_alter_membro_nivel_hierarquico'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkrapido',
            name='visibilidade',
            field=models.CharField(choices=[('geral', 'Todos os Usuários'), ('membros', 'Apenas Membros e Acima'), ('lideres', 'Líderes e Acima'), ('admin', 'Somente Administradores')], default='geral', max_length=20),
        ),
    ]
