# Generated by Django 6.0.5 on 2026-06-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_linkrapido_visibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='apelido',
            field=models.CharField(blank=True, help_text='Apelido ou nome comum pelo qual é conhecido (ajuda a Inteligência Artificial)', max_length=50, null=True),
        ),
    ]
