# Generated by Django 6.0.5 on 2026-06-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_membro_apelido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateDocumento',
        ),
    ]
