# Generated by Django 6.0.5 on 2026-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notificacaoglobal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('pendente', 'Pendente'), ('falha', 'Falha ao Enviar')], default='pendente', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('erro_mensagem', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de E-mail',
                'verbose_name_plural': 'Logs de E-mails',
                'ordering': ['-data_envio'],
            },
        ),
    ]
