# Generated by Django 6.0.5 on 2026-06-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(help_text='Caminho físico do arquivo de backup.', max_length=500)),
                ('tamanho_mb', models.DecimalField(decimal_places=2, help_text='Tamanho do arquivo em MB.', max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Backup de Banco de Dados',
                'verbose_name_plural': 'Backups de Banco de Dados',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
