# Generated by Django 6.0.5 on 2026-06-05 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_databasebackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('total_urls', models.IntegerField(default=0)),
                ('erros_encontrados', models.IntegerField(default=0)),
                ('log_texto', models.TextField()),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
