# Generated by Django 6.0.5 on 2026-06-12 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_spidertestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogImutavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('dados_acao', models.TextField()),
                ('hash_anterior', models.CharField(blank=True, max_length=64, null=True)),
                ('hash_atual', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Imutável (Zero-Trust)',
                'verbose_name_plural': 'Logs Imutáveis (Zero-Trust)',
                'ordering': ['-id'],
            },
        ),
    ]
