# Generated by Django 6.0.5 on 2026-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_logimutavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEngineerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('erro_analisado', models.TextField()),
                ('arquivo_modificado', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('detalhes', models.TextField()),
            ],
        ),
    ]
