# Generated by Django 6.0.5 on 2026-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_aiengineerlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticiaticker',
            options={'ordering': ['ordem'], 'verbose_name': 'Notícia Global (Dashboard)', 'verbose_name_plural': 'Notícias Globais (Dashboard)'},
        ),
        migrations.RemoveField(
            model_name='noticiaticker',
            name='texto',
        ),
        migrations.AddField(
            model_name='noticiaticker',
            name='mensagem',
            field=models.TextField(default='', help_text='Conteúdo da notícia'),
        ),
        migrations.AddField(
            model_name='noticiaticker',
            name='titulo',
            field=models.CharField(default='Destaque', help_text='Título da notícia', max_length=100),
        ),
    ]
