# Generated by Django 6.0.5 on 2026-06-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_noticiaticker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='status_conta',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado'), ('transferido', 'Transferido'), ('falecido', 'Falecido')], default='ativo', max_length=20),
        ),
    ]
