# Generated by Django 6.0.5 on 2026-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_membro_status_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, help_text='Token de Acesso Permanente (Meta Cloud API)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_ativo',
            field=models.BooleanField(default=False, help_text='Master switch. Se falso, nenhum WhatsApp será disparado.'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='ID do Número de Telefone (Meta Cloud API)', max_length=100, null=True),
        ),
    ]
