# Generated by Django 6.0.5 on 2026-06-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_configuracaosistema_whatsapp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_app_secret',
            field=models.CharField(blank=True, help_text='App Secret (Webhook HMAC SHA256)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_verify_token',
            field=models.CharField(blank=True, help_text='Verify Token (Webhook Challenge)', max_length=100, null=True),
        ),
    ]
