# Generated by Django 6.0.5 on 2026-06-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_configuracaosistema_whatsapp_app_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='intervalo_reenvio_emails_horas',
            field=models.IntegerField(default=1, help_text='Intervalo automático (em horas) para tentar reenviar e-mails que falharam.'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='anexos_json',
            field=models.TextField(blank=True, help_text='Lista serializada de caminhos de anexos', null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='corpo_html',
            field=models.TextField(blank=True, help_text='Cópia do HTML para permitir reenvio', null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='qtd_reenvios',
            field=models.IntegerField(default=0, help_text='Quantas vezes o sistema tentou reenviar'),
        ),
    ]
