# Generated by Django 6.0.5 on 2026-06-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_configuracaosistema_intervalo_reenvio_emails_horas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_numero', models.CharField(max_length=30)),
                ('template_usado', models.CharField(help_text='Nome do template na Meta ou tipo de envio', max_length=150)),
                ('corpo_json', models.TextField(blank=True, help_text='Payload original em JSON para reenvio exato', null=True)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('pendente', 'Pendente'), ('falha', 'Falha ao Enviar')], default='pendente', max_length=20)),
                ('qtd_reenvios', models.IntegerField(default=0, help_text='Quantas vezes o sistema tentou reenviar')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('erro_mensagem', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de WhatsApp',
                'verbose_name_plural': 'Logs de WhatsApp',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='intervalo_reenvio_whatsapp_horas',
            field=models.IntegerField(default=1, help_text='Intervalo automático (em horas) para tentar reenviar whatsapps que falharam.'),
        ),
    ]
