# Generated by Django 6.0.5 on 2026-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_logwhatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackup',
            name='enviado_nuvem',
            field=models.BooleanField(default=False, help_text='Indica se o backup já foi enviado para a nuvem.'),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='ID do arquivo no Google Drive.', max_length=255, null=True),
        ),
    ]
