# Generated by Django 6.0.5 on 2026-06-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_databasebackup_enviado_nuvem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='anotacoes_lideranca',
        ),
    ]
