# Generated by Django 6.0.5 on 2026-06-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_membro_anotacoes_lideranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='alerta_invasao_ativo',
            field=models.BooleanField(default=False, help_text='Se ativado, envia um alerta ao administrador quando alguém tentar acessar rotas sem permissão (Erro 403).'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='email_admin_alertas',
            field=models.EmailField(blank=True, help_text='Email do administrador que receberá os alertas de invasão.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='whatsapp_admin_alertas',
            field=models.CharField(default='5513991346297', help_text='Número de WhatsApp do administrador que receberá os alertas (Apenas números, com DDI e DDD).', max_length=20),
        ),
    ]
