# Generated by Django 6.0.5 on 2026-06-23 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_configuracaosistema_alerta_invasao_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaInvasao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('caminho_url', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas_invasao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Invasão',
                'verbose_name_plural': 'Alertas de Invasão',
                'ordering': ['-data_hora'],
            },
        ),
    ]
