# Generated by Django 6.0.5 on 2026-06-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alertainvasao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='habilidades',
        ),
    ]
