# Generated by Django 6.0.5 on 2026-06-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_membro_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='tamanho_calca',
            field=models.CharField(blank=True, help_text='Ex: 36, 38, 40, P, M, G', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='membro',
            name='tamanho_calcado',
            field=models.CharField(blank=True, help_text='Ex: 38, 40, 42', max_length=10, null=True),
        ),
    ]
