# Generated by Django 6.0.5 on 2026-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_membro_tamanho_calca_membro_tamanho_calcado'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='mfa_obrigatorio',
            field=models.BooleanField(default=False, help_text='Se marcado, o usuário será forçado a configurar o MFA no próximo login.', verbose_name='MFA Obrigatório'),
        ),
    ]
