# Generated by Django 6.0.5 on 2026-05-25 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_pdf_drive', models.URLField()),
                ('hash_assinatura_eletronica', models.CharField(editable=False, max_length=256)),
                ('data_geracao_aceite', models.DateTimeField(auto_now_add=True)),
                ('membro_assinante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_lgpd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnexoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_pdf_drive', models.URLField()),
                ('data_anexo', models.DateTimeField(auto_now_add=True)),
                ('documento_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='midia_lgpd.documentolgpd')),
            ],
        ),
    ]
