# Generated by Django 6.0.5 on 2026-05-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0001_initial'),
        ('midia_lgpd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Termo de Uso de Imagem v1', max_length=200)),
                ('conteudo_juridico', models.TextField(help_text='Texto completo do termo para o membro ler')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('is_ativo', models.BooleanField(default=True, help_text='Apenas um termo deve estar ativo por vez')),
            ],
        ),
        migrations.RemoveField(
            model_name='documentolgpd',
            name='membro_assinante',
        ),
        migrations.CreateModel(
            name='ArquivoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='arquivos/%Y/%m/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('is_publico_para_membros', models.BooleanField(default=False, help_text='Se marcado, voluntários comuns do setor poderão baixar o arquivo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_midia', to='gestao_membros.departamento')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssinaturaLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aceite', models.DateTimeField(auto_now_add=True)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_lgpd', to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='midia_lgpd.termolgpd')),
            ],
            options={
                'unique_together': {('membro', 'termo')},
            },
        ),
        migrations.DeleteModel(
            name='AnexoLGPD',
        ),
        migrations.DeleteModel(
            name='DocumentoLGPD',
        ),
    ]
