# Generated by Django 6.0.5 on 2026-05-25 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0007_departamento_logo_habilidade_departamento_and_more'),
        ('midia_lgpd', '0002_termolgpd_remove_documentolgpd_membro_assinante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Autorização de Acampamento', max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('conteudo_base', models.TextField(help_text='Corpo do contrato/documento. Use {{NOME}} para variáveis.')),
                ('campos_json', models.JSONField(default=list, help_text="Lista de campos: [{'nome': 'NOME', 'tipo': 'text', 'label': 'Nome Completo'}]")),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_acesso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_destino', models.EmailField(help_text='E-mail que receberá o link para assinatura', max_length=254)),
                ('nome_destino', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Assinatura'), ('assinado', 'Assinado/Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('dados_preenchidos', models.JSONField(blank=True, default=dict, null=True)),
                ('arquivo_pdf_final', models.FileField(blank=True, null=True, upload_to='documentos_assinados/%Y/%m/')),
                ('anexo_fisico_escaneado', models.FileField(blank=True, null=True, upload_to='documentos_escaneados/%Y/%m/')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_membros.departamento')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentos_gerados', to='midia_lgpd.documentotemplate')),
            ],
        ),
    ]
