# Generated by Django 6.0.5 on 2026-06-01 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0011_alter_configuracaoslotescala_tipo_evento'),
        ('midia_lgpd', '0003_documentotemplate_documentogerado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivomidia',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivomidia',
            name='extensao',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='arquivomidia',
            name='hash_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='arquivomidia',
            name='is_excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arquivomidia',
            name='tamanho_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentotemplate',
            name='css_canva',
            field=models.TextField(blank=True, help_text='Estilos CSS do Editor Canva'),
        ),
        migrations.AddField(
            model_name='documentotemplate',
            name='html_canva',
            field=models.TextField(blank=True, help_text='Estrutura HTML do Editor Canva'),
        ),
        migrations.AddField(
            model_name='documentotemplate',
            name='json_canva',
            field=models.JSONField(blank=True, help_text='Grafo de elementos GrapesJS/Fabric', null=True),
        ),
        migrations.CreateModel(
            name='PastaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('is_excluida', models.BooleanField(default=False)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='gestao_membros.departamento')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='midia_lgpd.pastavirtual')),
            ],
        ),
        migrations.CreateModel(
            name='CompartilhamentoPasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateTimeField(blank=True, null=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_compartilhadas', to='gestao_membros.departamento')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='midia_lgpd.pastavirtual')),
            ],
        ),
        migrations.AddField(
            model_name='arquivomidia',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='midia_lgpd.pastavirtual'),
        ),
    ]
