# Generated by Django 6.0.5 on 2026-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia_lgpd', '0004_arquivomidia_data_exclusao_arquivomidia_extensao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotemplate',
            name='identificador_sistema',
            field=models.CharField(blank=True, help_text='Código interno para disparo automático (ex: email_boas_vindas)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='documentotemplate',
            name='tipo_documento',
            field=models.CharField(choices=[('pdf_lgpd', 'PDF Assinatura (LGPD/Contratos)'), ('pdf_escala', 'PDF Escala de Voluntários'), ('email', 'E-mail do Sistema')], default='pdf_lgpd', max_length=20),
        ),
    ]
