# Generated by Django 6.0.5 on 2026-06-02 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0012_acaodisciplinar_avaliacaomembro_ocorrencia'),
        ('midia_lgpd', '0005_documentotemplate_identificador_sistema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivomidia',
            name='gdrive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arquivomidia',
            name='gdrive_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pastavirtual',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pastavirtual',
            name='gdrive_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='arquivomidia',
            name='arquivo',
            field=models.FileField(blank=True, help_text='Arquivo local (Legado ou Temporário)', null=True, upload_to='arquivos/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='PermissaoPVDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('leitor', 'Pode Visualizar e Baixar'), ('editor', 'Pode Fazer Upload e Editar'), ('admin', 'Administrador (Pode Excluir)')], default='leitor', max_length=20)),
                ('data_concessao', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateTimeField(blank=True, help_text='Se preenchido, o acesso expira nesta data.', null=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('alvo_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_recebidas', to='gestao_membros.departamento')),
                ('alvo_membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('concedido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissoes_concedidas', to=settings.AUTH_USER_MODEL)),
                ('pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='midia_lgpd.pastavirtual')),
            ],
        ),
    ]
