# Generated by Django 6.0.5 on 2026-06-02 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0012_acaodisciplinar_avaliacaomembro_ocorrencia'),
        ('midia_lgpd', '0006_arquivomidia_gdrive_file_id_arquivomidia_gdrive_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivomidia',
            name='dono_membro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_pessoais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastavirtual',
            name='dono_membro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastas_pessoais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastavirtual',
            name='is_sistema',
            field=models.BooleanField(default=False, help_text='Se marcado, a pasta não pode ser excluída ou renomeada'),
        ),
        migrations.AddField(
            model_name='pastavirtual',
            name='tipo_pasta',
            field=models.CharField(choices=[('raiz', 'Raiz do Sistema'), ('raiz_deptos', 'Raiz de Departamentos'), ('raiz_usuarios', 'Raiz de Usuários'), ('departamento', 'Pasta de Departamento'), ('usuario', 'Pasta Pessoal de Usuário'), ('compartilhados', 'Compartilhados Comigo'), ('normal', 'Pasta Normal')], default='normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='arquivomidia',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_midia', to='gestao_membros.departamento'),
        ),
        migrations.AlterField(
            model_name='pastavirtual',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pastavirtual',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='gestao_membros.departamento'),
        ),
    ]
