# Generated by Django 6.0.5 on 2026-06-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midia_lgpd', '0007_arquivomidia_dono_membro_pastavirtual_dono_membro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentotemplate',
            name='criado_por',
        ),
        migrations.DeleteModel(
            name='DocumentoGerado',
        ),
        migrations.DeleteModel(
            name='DocumentoTemplate',
        ),
    ]
