# Generated by Django 6.0.5 on 2026-06-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia_lgpd', '0008_remove_documentotemplate_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissaopvdrive',
            name='arquivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='midia_lgpd.arquivomidia'),
        ),
        migrations.AddField(
            model_name='permissaopvdrive',
            name='foi_acessado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissaopvdrive',
            name='is_autodestruir',
            field=models.BooleanField(default=False, help_text='Se marcado, o arquivo some do compartilhamento após o primeiro acesso'),
        ),
        migrations.AddField(
            model_name='permissaopvdrive',
            name='senha_acesso',
            field=models.CharField(blank=True, help_text='Hash de senha para acesso seguro', max_length=128, null=True),
        ),
    ]
