# Generated by Django 6.0.5 on 2026-06-19 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia_lgpd', '0009_permissaopvdrive_arquivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assinaturalgpd',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='termolgpd',
            name='tipo',
            field=models.CharField(choices=[('membro', 'Membro / Voluntário'), ('visitante', 'Visitante Geral'), ('crianca', 'Criança / Menor de Idade')], default='membro', max_length=20),
        ),
        migrations.AlterField(
            model_name='termolgpd',
            name='is_ativo',
            field=models.BooleanField(default=True, help_text='Apenas um termo ativo por tipo'),
        ),
        migrations.CreateModel(
            name='RegistroAceiteLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('nome_crianca', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Criança (Opcional)')),
                ('token_acesso', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='lgpd/documentos_assinados/', verbose_name='PDF Gerado')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aceites_lgpd_v2', to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='midia_lgpd.termolgpd')),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
