# Generated by Django 6.0.5 on 2026-06-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midia_lgpd', '0010_alter_assinaturalgpd_unique_together_termolgpd_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaceitelgpd',
            name='historico_alteracoes',
            field=models.JSONField(blank=True, default=list, help_text='Log JSON das ações de aceite/recusa'),
        ),
    ]
