# Generated by Django 6.0.5 on 2026-06-05 15:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('midia_lgpd', '0007_arquivomidia_dono_membro_pastavirtual_dono_membro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.CharField(blank=True, help_text='ID automático ou Código de Barras manual', max_length=50, unique=True)),
                ('nome', models.CharField(help_text='Ex: Arroz 5kg, Câmera Sony, Microfone Shure', max_length=200)),
                ('subcategoria', models.CharField(blank=True, max_length=100)),
                ('tipo_item', models.CharField(choices=[('permanente', 'Ativo Permanente (Devolução Obrigatória)'), ('consumo', 'Item de Consumo (Alimentos/Descartáveis)')], default='permanente', max_length=20)),
                ('quantidade_estoque', models.PositiveIntegerField(default=1)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField(blank=True, help_text='Para alimentos perecíveis', null=True)),
                ('origem', models.CharField(choices=[('comprado', 'Comprado (Igreja)'), ('doado', 'Doado (Membros/Terceiros)'), ('banco_alimentos', 'Banco de Alimentos Municipal'), ('transferido', 'Transferido de Filial'), ('desconhecido', 'Legado / Desconhecido')], default='desconhecido', max_length=20)),
                ('fornecedor_doador', models.CharField(blank=True, help_text='Loja ou Pessoa que doou', max_length=200)),
                ('localizacao', models.CharField(blank=True, help_text='Ex: Prateleira A, Armário de Som', max_length=150)),
                ('destino_uso', models.CharField(blank=True, help_text='Para onde vai esse item? (Ex: Cestas Básicas, Culto Jovem)', max_length=200)),
                ('status_item', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado / Em Uso Externo'), ('manutencao', 'Em Manutenção'), ('consumido', 'Consumido / Esgotado')], default='disponivel', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('foto_item', models.ImageField(blank=True, null=True, upload_to='fotos/almoxarifado/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='almoxarifado.categoriaitem')),
                ('pasta_pv_drive', models.ForeignKey(blank=True, help_text='Pasta com todas as NF e comprovantes do item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='midia_lgpd.pastavirtual')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoAlmoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retirada', 'Retirada (-)'), ('devolucao', 'Devolução (+)'), ('entrada_estoque', 'Entrada de Estoque (+)'), ('baixa', 'Baixa Definitiva (-)')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('nome_digitado', models.CharField(help_text='Nome digitado no QR Code Público', max_length=200)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('assinatura_digital_hash', models.CharField(editable=False, help_text='Hash SHA-256 de segurança', max_length=256)),
                ('observacao', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='almoxarifado.itemalmoxarifado')),
                ('membro_vinculado', models.ForeignKey(blank=True, help_text='Membro vinculado via IA/Fuzzy Match', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
