# Generated by Django 6.0.5 on 2026-05-25 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_membros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_patrimonio', models.CharField(help_text='Código único de barra ou serial', max_length=50, unique=True)),
                ('categoria', models.CharField(default='Geral', max_length=100)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado'), ('manutencao', 'Em Manutenção'), ('quebrado', 'Danificado / Quebrado')], default='disponivel', max_length=20)),
                ('data_aquisicao', models.DateField(auto_now_add=True)),
                ('data_ultima_manutencao', models.DateField(blank=True, null=True)),
                ('departamento_dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to='gestao_membros.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, help_text='Anotações de defeitos ou estado do item na retirada', null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_emprestimos', to='almoxarifado.ativo')),
                ('membro_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_emprestados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
