# Generated by Django 6.0.5 on 2026-06-05 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='almoxarifado.categoriaitem')),
            ],
            options={
                'unique_together': {('nome', 'categoria')},
            },
        ),
        migrations.AlterField(
            model_name='itemalmoxarifado',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='almoxarifado.subcategoriaitem'),
        ),
    ]
