# Generated by Django 6.0.5 on 2026-05-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
        ('gestao_membros', '0002_indisponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Arroz 5kg, Feijão Preto', max_length=150)),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade em unidades/caixas')),
                ('data_vencimento', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_membros.departamento')),
            ],
        ),
    ]
