# Generated by Django 6.0.5 on 2026-05-25 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_alimentolote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('data_retorno_prevista', models.DateField(blank=True, null=True)),
                ('data_retorno_real', models.DateField(blank=True, null=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('oficina_tecnico', models.CharField(help_text='Nome da oficina ou pessoa responsável pelo conserto', max_length=200)),
                ('descricao_problema', models.TextField()),
                ('solucao_aplicada', models.TextField(blank=True, null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencoes', to='almoxarifado.ativo')),
            ],
        ),
    ]
