# Generated by Django 6.0.5 on 2026-06-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_subcategoriaitem_alter_itemalmoxarifado_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='condicao_fisica',
            field=models.CharField(choices=[('nova', 'Nova / Excelente'), ('boa', 'Boa'), ('regular', 'Regular / Intermediária'), ('ruim', 'Ruim')], default='nova', max_length=20),
        ),
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='status_pagamento',
            field=models.CharField(choices=[('quitado', 'Quitado'), ('parcelado', 'Parcelado'), ('doacao', 'Doação/Grátis'), ('nao_se_aplica', 'Não se Aplica')], default='nao_se_aplica', max_length=20),
        ),
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='valor_monetario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemalmoxarifado',
            name='status_item',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado / Em Uso Externo'), ('manutencao', 'Em Manutenção'), ('consumido', 'Consumido / Esgotado'), ('alocado', 'Alocado (Uso Fixo)'), ('descartado', 'Descartado / Baixa')], default='disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemalmoxarifado',
            name='tipo_item',
            field=models.CharField(choices=[('permanente', 'Ativo Permanente (Devolução Obrigatória)'), ('consumo', 'Item de Consumo (Alimentos/Descartáveis)'), ('fixo', 'Ativo Fixo (Alocado Permanentemente, não devolvido)')], default='permanente', max_length=20),
        ),
    ]
