# Generated by Django 6.0.5 on 2026-05-25 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_manutencao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='alimentolote',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='alimentolote',
            name='fornecedor_doador',
            field=models.CharField(blank=True, help_text='Nome do supermercado ou pessoa/instituição doadora', max_length=200),
        ),
        migrations.AddField(
            model_name='alimentolote',
            name='foto_lote',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/alimentos/'),
        ),
        migrations.AddField(
            model_name='alimentolote',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Ex: Prateleira B, Geladeira 1', max_length=150),
        ),
        migrations.AddField(
            model_name='alimentolote',
            name='origem',
            field=models.CharField(choices=[('comprado', 'Comprado (Nota Fiscal)'), ('doado', 'Doado (Membro/Instituição)'), ('banco_alimentos', 'Banco de Alimentos Municipal')], default='doado', max_length=20),
        ),
        migrations.AddField(
            model_name='alimentolote',
            name='quantidade_atual',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade restante'),
        ),
        migrations.AddField(
            model_name='alimentolote',
            name='quantidade_inicial',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade original'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='anexo_comprovante',
            field=models.FileField(blank=True, help_text='Nota fiscal ou recibo', null=True, upload_to='comprovantes/ativos/'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='fornecedor_doador',
            field=models.CharField(blank=True, help_text='Loja de compra ou nome do doador', max_length=200),
        ),
        migrations.AddField(
            model_name='ativo',
            name='foto_item',
            field=models.ImageField(blank=True, help_text='Foto real do equipamento', null=True, upload_to='fotos/ativos/'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='origem',
            field=models.CharField(choices=[('comprado', 'Comprado'), ('doado', 'Doado'), ('transferido', 'Transferido (Filial)'), ('desconhecido', 'Desconhecido / Legado')], default='desconhecido', max_length=20),
        ),
        migrations.AddField(
            model_name='ativo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor monetário (R$)', max_digits=10),
        ),
        migrations.AddField(
            model_name='ativo',
            name='categoria_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='almoxarifado.categoriaativo'),
        ),
        migrations.CreateModel(
            name='SubCategoriaAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='almoxarifado.categoriaativo')),
            ],
        ),
        migrations.AddField(
            model_name='ativo',
            name='subcategoria_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos', to='almoxarifado.subcategoriaativo'),
        ),
        migrations.CreateModel(
            name='TransacaoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (+)'), ('saida', 'Saída / Consumo (-)')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('destino_origem', models.CharField(help_text='Para quem foi entregue? (Saída) ou Quem repôs? (Entrada)', max_length=200)),
                ('observacao', models.TextField(blank=True)),
                ('anexo_comprovante', models.FileField(blank=True, help_text='Foto do recibo ou assinatura da família', null=True, upload_to='comprovantes/alimentos/')),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='almoxarifado.alimentolote')),
                ('membro_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
