# Generated by Django 6.0.5 on 2026-06-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_itemalmoxarifado_condicao_fisica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemalmoxarifado',
            name='exige_aprovacao',
            field=models.BooleanField(default=False, help_text='Se marcado, a retirada deste item ficará pendente até aprovação de um Gestor.'),
        ),
        migrations.AddField(
            model_name='movimentacaoalmoxarifado',
            name='email_digitado',
            field=models.EmailField(blank=True, help_text='Email para envio do Termo de Cautela Automático', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoalmoxarifado',
            name='status_aprovacao',
            field=models.CharField(choices=[('aprovado', 'Aprovado / Automático'), ('pendente', 'Pendente de Aprovação'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=20),
        ),
    ]
