# Generated by Django 6.0.5 on 2026-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_itemalmoxarifado_exige_aprovacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemalmoxarifado',
            name='id_unico',
            field=models.CharField(blank=True, help_text='ID automático ou Código de Barras manual', max_length=50, null=True, unique=True),
        ),
    ]
