# Generated by Django 6.0.5 on 2026-05-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_categoriaativo_remove_alimentolote_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Se estiver em Uso Fixo, qual é a sala/local?', max_length=150),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso_fixo', 'Em Uso Fixo / Local'), ('emprestado', 'Emprestado'), ('manutencao', 'Em Manutenção'), ('quebrado', 'Danificado / Quebrado')], default='disponivel', max_length=20),
        ),
    ]
