# Generated by Django 6.0.5 on 2026-05-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_ativo_localizacao_alter_ativo_status'),
        ('gestao_membros', '0007_departamento_logo_habilidade_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentolote',
            name='anexo_nota_fiscal',
            field=models.FileField(blank=True, help_text='Nota Fiscal de compra ou termo de doação do lote todo.', null=True, upload_to='comprovantes/alimentos_lotes/'),
        ),
        migrations.AlterField(
            model_name='alimentolote',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alimentolote',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_alimentos', to='gestao_membros.departamento'),
        ),
    ]
