# Generated by Django 6.0.5 on 2026-05-27 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0006_alimentolote_anexo_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentolote',
            name='anexo_nota_fiscal',
            field=models.FileField(blank=True, help_text='Nota Fiscal de compra ou termo de doação do lote todo.', null=True, upload_to='comprovantes/alimentos_lotes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='alimentolote',
            name='foto_lote',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/alimentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='anexo_comprovante',
            field=models.FileField(blank=True, help_text='Nota fiscal ou recibo', null=True, upload_to='comprovantes/ativos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='foto_item',
            field=models.ImageField(blank=True, help_text='Foto real do equipamento', null=True, upload_to='fotos/ativos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='transacaoalimento',
            name='anexo_comprovante',
            field=models.FileField(blank=True, help_text='Foto do recibo ou assinatura da família', null=True, upload_to='comprovantes/alimentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
    ]
