# Generated by Django 6.0.5 on 2026-06-11 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conjuge_1', models.CharField(max_length=150, verbose_name='Nome Cônjuge 1')),
                ('nome_conjuge_2', models.CharField(max_length=150, verbose_name='Nome Cônjuge 2')),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Cônjuge 1')),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Cônjuge 2')),
                ('telefone_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Cônjuge 1')),
                ('telefone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Cônjuge 2')),
                ('status_relacionamento', models.CharField(choices=[('Namorados', 'Namorados'), ('Noivos', 'Noivos'), ('Casados', 'Casados'), ('Em Crise', 'Em Crise'), ('Separados', 'Separados')], default='Casados', max_length=50, verbose_name='Status do Relacionamento')),
                ('data_aniversario_casamento', models.DateField(blank=True, null=True, verbose_name='Data do Casamento (Bodas)')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('trilha_noivos_etapa', models.IntegerField(default=0, help_text='0: N/A, 1: Iniciado, 2: Curso Feito, 3: Aconselhamento, 4: Altar', verbose_name='Etapa Trilha de Noivos')),
            ],
        ),
        migrations.CreateModel(
            name='CursoCasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor_curso', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Curso')),
                ('carga_horaria', models.IntegerField(default=10, verbose_name='Carga Horária (Horas)')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do Evento')),
                ('data_evento', models.DateTimeField(verbose_name='Data e Hora')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAconselhamentoCasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sessao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pastor_conselheiro', models.CharField(max_length=100, verbose_name='Pastor / Conselheiro')),
                ('observacoes', models.TextField(verbose_name='Observações da Sessão')),
                ('nivel_crise', models.IntegerField(default=1, help_text='1: Saudável, 5: Alerta Vermelho / Separação', verbose_name='Nível de Crise (1 a 5)')),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_aconselhamento', to='ministerio_casais.casal')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaCursoCasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('status_pagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Bolsa Parcial', 'Bolsa Parcial'), ('Bolsa Integral', 'Bolsa Integral')], default='Pendente', max_length=50, verbose_name='Status Financeiro')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago')),
                ('percentual_conclusao', models.IntegerField(default=0, verbose_name='Progresso (%)')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado / Certificado')),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_cursos', to='ministerio_casais.casal')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='ministerio_casais.cursocasal')),
            ],
        ),
        migrations.CreateModel(
            name='PresencaEventoCasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmou_presenca', models.BooleanField(default=False, verbose_name='Confirmou Presença?')),
                ('compareceu', models.BooleanField(default=False, verbose_name='Compareceu?')),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_presentes', to='ministerio_casais.casal')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='ministerio_casais.eventocasal')),
            ],
        ),
    ]
