# Generated by Django 6.0.5 on 2026-06-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio_casais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casal',
            name='foto_casal',
            field=models.ImageField(blank=True, null=True, upload_to='casais/fotos/', verbose_name='Foto do Casal'),
        ),
        migrations.AddField(
            model_name='casal',
            name='foto_conjuge_1',
            field=models.ImageField(blank=True, null=True, upload_to='casais/fotos/', verbose_name='Foto Cônjuge 1'),
        ),
        migrations.AddField(
            model_name='casal',
            name='foto_conjuge_2',
            field=models.ImageField(blank=True, null=True, upload_to='casais/fotos/', verbose_name='Foto Cônjuge 2'),
        ),
        migrations.AddField(
            model_name='historicoaconselhamentocasal',
            name='atendimento_para',
            field=models.CharField(choices=[('Casal', 'Casal'), ('Apenas Cônjuge 1', 'Apenas Cônjuge 1'), ('Apenas Cônjuge 2', 'Apenas Cônjuge 2')], default='Casal', max_length=50, verbose_name='Atendimento para'),
        ),
        migrations.AddField(
            model_name='matriculacursocasal',
            name='certificado_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='casais/certificados/', verbose_name='Arquivo do Certificado'),
        ),
    ]
