# Generated by Django 6.0.5 on 2026-06-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio_casais', '0002_casal_foto_casal_casal_foto_conjuge_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casal',
            name='arquivado',
            field=models.BooleanField(default=False, verbose_name='Arquivado/Saiu'),
        ),
        migrations.AddField(
            model_name='cursocasal',
            name='compra_camiseta',
            field=models.BooleanField(default=False, verbose_name='Requer Camiseta?'),
        ),
        migrations.AddField(
            model_name='cursocasal',
            name='emite_certificado',
            field=models.BooleanField(default=False, verbose_name='Emite Certificado?'),
        ),
    ]
