# Generated by Django 6.0.5 on 2026-06-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio_casais', '0003_casal_arquivado_cursocasal_compra_camiseta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursocasal',
            name='dias_semana',
            field=models.CharField(blank=True, help_text='Ex: Segunda, Quarta', max_length=150, null=True, verbose_name='Dias da Semana'),
        ),
        migrations.CreateModel(
            name='PagamentoCursoCasal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Transferência', 'Transferência')], max_length=50, verbose_name='Forma de Pagamento')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pagamentos', to='ministerio_casais.matriculacursocasal')),
            ],
        ),
    ]
