# Generated by Django 6.0.5 on 2026-06-12 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio_casais', '0004_cursocasal_dias_semana_pagamentocursocasal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostagemCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Postagem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição / Conteúdo')),
                ('tipo', models.CharField(choices=[('Aviso', 'Aviso'), ('Material', 'Material de Estudo (Download)'), ('Tarefa', 'Tarefa / Atividade (Requer Envio)')], default='Aviso', max_length=50, verbose_name='Tipo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='casais/cursos/materiais/', verbose_name='Arquivo Anexo')),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite de Entrega (Para Tarefas)')),
            ],
        ),
        migrations.RemoveField(
            model_name='matriculacursocasal',
            name='curso',
        ),
        migrations.AddField(
            model_name='casal',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=True, verbose_name='Trocar Senha no Próximo Login'),
        ),
        migrations.AddField(
            model_name='casal',
            name='senha',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha de Acesso'),
        ),
        migrations.AddField(
            model_name='matriculacursocasal',
            name='token_acesso',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token Mágico de Acesso'),
        ),
        migrations.CreateModel(
            name='EntregaAtividadeAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_enviado', models.FileField(upload_to='casais/cursos/entregas/', verbose_name='Arquivo Enviado')),
                ('comentario_aluno', models.TextField(blank=True, null=True, verbose_name='Comentário do Aluno')),
                ('data_entrega', models.DateTimeField(auto_now_add=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota (Opcional)')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tarefas', to='ministerio_casais.matriculacursocasal')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='ministerio_casais.postagemcurso')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=100, verbose_name='Nome/Número da Turma')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('Aberta', 'Aberta (Matrículas Abertas)'), ('Em Andamento', 'Em Andamento'), ('Concluída', 'Concluída')], default='Aberta', max_length=50, verbose_name='Status da Turma')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='ministerio_casais.cursocasal')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_lecionadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='ministerio_casais.turmacurso')),
            ],
        ),
        migrations.AddField(
            model_name='postagemcurso',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='ministerio_casais.turmacurso'),
        ),
        migrations.AddField(
            model_name='matriculacursocasal',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='ministerio_casais.turmacurso'),
        ),
    ]
