# Generated by Django 6.0.5 on 2026-06-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio_casais', '0005_postagemcurso_remove_matriculacursocasal_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculacursocasal',
            name='status_matricula',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Aprovado', 'Aprovado'), ('Reprovado por Falta', 'Reprovado por Falta'), ('Desistente', 'Desistente')], default='Ativa', max_length=50, verbose_name='Status da Matrícula'),
        ),
        migrations.AddField(
            model_name='turmacurso',
            name='limite_faltas',
            field=models.IntegerField(default=3, help_text='Quantidade de faltas permitidas antes da reprovação', verbose_name='Limite Máximo de Faltas'),
        ),
        migrations.AddField(
            model_name='turmacurso',
            name='percentual_presenca_minimo',
            field=models.IntegerField(default=75, help_text='Se atingir as duas regras (A e B), o aluno reprova por falta', verbose_name='Percentual de Presença Mínimo (%)'),
        ),
        migrations.CreateModel(
            name='AulaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título/Tema da Aula')),
                ('data_aula', models.DateField(verbose_name='Data da Aula')),
                ('realizada', models.BooleanField(default=False, verbose_name='Aula Realizada / Chamada Feita')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='ministerio_casais.turmacurso')),
            ],
        ),
        migrations.CreateModel(
            name='PresencaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True, verbose_name='Presente?')),
                ('justificada', models.BooleanField(default=False, verbose_name='Falta Justificada/Abonada?')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='ministerio_casais.aulaturma')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_presenca', to='ministerio_casais.matriculacursocasal')),
            ],
        ),
    ]
