# Generated by Django 6.0.5 on 2026-06-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio_casais', '0006_matriculacursocasal_status_matricula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursocasal',
            name='carga_horaria',
        ),
        migrations.RemoveField(
            model_name='cursocasal',
            name='compra_camiseta',
        ),
        migrations.RemoveField(
            model_name='cursocasal',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='cursocasal',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='cursocasal',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='cursocasal',
            name='emite_certificado',
        ),
        migrations.RemoveField(
            model_name='cursocasal',
            name='valor_curso',
        ),
        migrations.RemoveField(
            model_name='turmacurso',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='turmacurso',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='postagemcurso',
            name='alunos_especificos',
            field=models.ManyToManyField(blank=True, help_text='Se vazio, vai para todos da turma.', related_name='postagens_diretas', to='ministerio_casais.matriculacursocasal'),
        ),
        migrations.AddField(
            model_name='turmacurso',
            name='carga_horaria',
            field=models.IntegerField(default=10, verbose_name='Carga Horária Total (Horas)'),
        ),
        migrations.AddField(
            model_name='turmacurso',
            name='compra_camiseta',
            field=models.BooleanField(default=False, verbose_name='Requer Camiseta?'),
        ),
        migrations.AddField(
            model_name='turmacurso',
            name='dias_semana',
            field=models.CharField(blank=True, help_text='Ex: Segunda, Quarta', max_length=150, null=True, verbose_name='Dias da Semana'),
        ),
        migrations.AddField(
            model_name='turmacurso',
            name='duracao_aula_horas',
            field=models.IntegerField(default=2, verbose_name='Duração por Aula (Horas)'),
        ),
        migrations.AddField(
            model_name='turmacurso',
            name='emite_certificado',
            field=models.BooleanField(default=False, verbose_name='Emite Certificado?'),
        ),
        migrations.AddField(
            model_name='turmacurso',
            name='valor_curso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Material/Inscrição'),
        ),
    ]
