# Generated by Django 6.0.5 on 2026-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio_casais', '0007_remove_cursocasal_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmacurso',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
