# Generated by Django 6.0.5 on 2026-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio_casais', '0008_turmacurso_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='casal',
            name='nivel_crise_atual',
            field=models.IntegerField(default=1, help_text='1: Saudável, 2: Atritos Leves, 3: Conflitos Moderados, 4: Alerta Laranja, 5: Alerta Vermelho', verbose_name='Nível de Crise Atual'),
        ),
    ]
