# Generated by Django 6.0.5 on 2026-06-26 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministerio_casais', '0009_casal_nivel_crise_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocasal',
            name='data_evento',
        ),
        migrations.AddField(
            model_name='eventocasal',
            name='capacidade_maxima',
            field=models.IntegerField(default=50, verbose_name='Capacidade Máxima (Casais)'),
        ),
        migrations.AddField(
            model_name='eventocasal',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Término'),
        ),
        migrations.AddField(
            model_name='eventocasal',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora de Início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventocasal',
            name='status',
            field=models.CharField(choices=[('Planejamento', 'Em Planejamento'), ('Aberto', 'Inscrições Abertas'), ('Lotado', 'Lotado'), ('Encerrado', 'Encerrado')], default='Aberto', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='eventocasal',
            name='tipo',
            field=models.CharField(choices=[('Retiro', 'Retiro de Casais'), ('Jantar', 'Jantar de Casais'), ('Encontro', 'Encontro / Reunião'), ('Outros', 'Outros')], default='Retiro', max_length=50, verbose_name='Tipo de Evento'),
        ),
        migrations.AddField(
            model_name='eventocasal',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Base (Opcional se usar lotes)'),
        ),
        migrations.AlterField(
            model_name='eventocasal',
            name='local',
            field=models.CharField(max_length=200, verbose_name='Local / Hotel'),
        ),
        migrations.CreateModel(
            name='DespesaMinisterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despesa', models.DateField(verbose_name='Data da Despesa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Gasto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('categoria', models.CharField(choices=[('Alimentação', 'Alimentação / Coffee Break'), ('Local', 'Locação de Espaço / Hotel'), ('Material', 'Materiais Gráficos e Brindes'), ('Preletor', 'Preletores / Convidados / Ofertas'), ('Marketing', 'Marketing / Impulsionamento'), ('Outros', 'Outros Gastos')], max_length=50, verbose_name='Categoria')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='casais/financeiro/comprovantes/', verbose_name='Comprovante / Recibo')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('evento_vinculado', models.ForeignKey(blank=True, help_text='Opcional. Vincule se o gasto foi para um evento específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='ministerio_casais.eventocasal')),
            ],
        ),
        migrations.CreateModel(
            name='LoteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Lote')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data_limite', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='ministerio_casais.eventocasal')),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status_pagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Pago Parcialmente'), ('Pago', 'Pago Integralmente'), ('Isento', 'Isento/Cortesia')], default='Pendente', max_length=50, verbose_name='Status de Pagamento')),
                ('valor_total_devido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Devido')),
                ('quarto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alojamento / Quarto')),
                ('observacoes_medicas', models.TextField(blank=True, null=True, verbose_name='Restrições Alimentares / Observações')),
                ('presente', models.BooleanField(default=False, verbose_name='Check-in / Presente?')),
                ('casal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_inscritos', to='ministerio_casais.casal')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='ministerio_casais.eventocasal')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministerio_casais.loteevento')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoInscricaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Pagamento')),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Transferência', 'Transferência')], max_length=50, verbose_name='Forma de Pagamento')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='ministerio_casais.inscricaoevento')),
            ],
        ),
        migrations.DeleteModel(
            name='PresencaEventoCasal',
        ),
    ]
