# Generated by Django 6.0.5 on 2026-05-25 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_membros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_escala', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('tipo_evento', models.CharField(choices=[('quarta', 'Quarta-Feira (20h-22h)'), ('domingo_manha', 'Domingo Manhã (09:30-11:30)'), ('domingo_noite', 'Domingo Noite (19:30-21:30)'), ('evento_extra', 'Evento Extraordinário')], max_length=20)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Confirmação'), ('confirmado', 'Confirmado'), ('substituido', 'Substituído'), ('falta_justificada', 'Falta Justificada')], default='aguardando', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('departamento_alocado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='gestao_membros.departamento')),
                ('membro_escalado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'constraints': [models.UniqueConstraint(fields=('membro_escalado', 'data_escala', 'horario_inicio'), name='unique_membro_escala_horario_zerotrust')],
            },
        ),
    ]
