# Generated by Django 6.0.5 on 2026-05-25 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
        ('gestao_membros', '0006_remove_departamento_habilidades_requeridas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='funcao_alocada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas', to='gestao_membros.funcao'),
        ),
    ]
