# Generated by Django 6.0.5 on 2026-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0002_escala_funcao_alocada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('substituido', 'Substituído'), ('falta_justificada', 'Falta Justificada')], default='confirmado', max_length=20),
        ),
    ]
