# Generated by Django 6.0.5 on 2026-05-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0003_alter_escala_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho (Não visível)'), ('confirmado', 'Confirmado'), ('substituido', 'Substituído'), ('falta_justificada', 'Falta Justificada')], default='confirmado', max_length=20),
        ),
    ]
