# Generated by Django 6.0.5 on 2026-05-27 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0004_alter_escala_status'),
        ('gestao_membros', '0008_alter_departamento_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='departamento_alocado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_individuais', to='gestao_membros.departamento'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='funcao_alocada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_individuais', to='gestao_membros.funcao'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='membro_escalado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_individuais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escala',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('substituido', 'Substituído'), ('falta_justificada', 'Falta Justificada')], default='confirmado', max_length=20),
        ),
        migrations.CreateModel(
            name='CompetenciaEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(help_text='Ex: 05/2026', max_length=7)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho (Não visível)'), ('publicada', 'Publicada')], default='rascunho', max_length=20)),
                ('pdf_gerado', models.FileField(blank=True, null=True, upload_to='escalas/pdfs/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_escala', to='gestao_membros.departamento')),
            ],
            options={
                'verbose_name': 'Competência de Escala',
                'verbose_name_plural': 'Competências de Escalas',
                'unique_together': {('departamento', 'mes_ano')},
            },
        ),
        migrations.AddField(
            model_name='escala',
            name='competencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='escalas.competenciaescala'),
        ),
    ]
