# Generated by Django 6.0.5 on 2026-05-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0005_alter_escala_departamento_alocado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='tipo_evento',
            field=models.CharField(choices=[('segunda_oracao', 'Segunda: Culto de Oração (20:00 - 21:00)'), ('quarta_profetica', 'Quarta: Quarta Profética (20:00 - 22:00)'), ('quinta_saber', 'Quinta: Quinta do Saber (19:30 - 20:30)'), ('domingo_manha', 'Domingo da Família: Manhã (09:30 - 11:30)'), ('domingo_noite', 'Domingo da Família: Noite (19:30 - 21:30)'), ('eventos', 'Eventos Extraordinários')], max_length=20),
        ),
    ]
