# Generated by Django 6.0.5 on 2026-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0006_alter_escala_tipo_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Culto de Oração, Santa Ceia, Atendimento Pastoral', max_length=150)),
                ('tipo', models.CharField(choices=[('padrao', 'Padrão (Recorrente)'), ('extra', 'Extraordinário (Único / Data Específica)')], default='padrao', max_length=20)),
                ('dia_semana', models.IntegerField(blank=True, help_text='0=Seg, 1=Ter, 2=Qua, 3=Qui, 4=Sex, 5=Sáb, 6=Dom', null=True)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('horario_inicio', models.TimeField(default='19:30')),
                ('horario_fim', models.TimeField(default='21:30')),
                ('chave_slug', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Culto / Evento',
                'verbose_name_plural': 'Tipos de Cultos e Eventos',
            },
        ),
        migrations.AlterField(
            model_name='escala',
            name='tipo_evento',
            field=models.CharField(max_length=50),
        ),
    ]
