# Generated by Django 6.0.5 on 2026-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0007_cultoevento_alter_escala_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='tipo_evento',
            field=models.CharField(max_length=200),
        ),
    ]
