# Generated by Django 6.0.5 on 2026-06-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0008_alter_escala_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='checkin_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escala',
            name='data_hora_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('presente', 'Presente (Check-in Realizado)'), ('substituido', 'Substituído'), ('falta_justificada', 'Falta Justificada')], default='confirmado', max_length=20),
        ),
    ]
