# Generated by Django 6.0.5 on 2026-06-15 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTesouraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sede', models.EmailField(blank=True, help_text='E-mail da Sede para recebimento do relatório mensal', max_length=254, null=True)),
                ('nome_recebedor_sede', models.CharField(blank=True, help_text='Nome da pessoa ou departamento responsável na Sede', max_length=150, null=True)),
                ('planilha_padrao_sede', models.FileField(blank=True, help_text='Upload da planilha padrão (template) exigida pela Sede. A IA preencherá este arquivo.', null=True, upload_to='tesouraria/templates_sede/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])])),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Tesouraria',
                'verbose_name_plural': 'Configurações da Tesouraria',
            },
        ),
    ]
