# Generated by Django 6.0.5 on 2026-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0002_configuracaotesouraria'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='impostos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de impostos cobrados na nota', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='is_parcelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='numero_parcelas',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='parcela_atual',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
