# Generated by Django 6.0.5 on 2026-06-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0003_lancamento_forma_pagamento_lancamento_impostos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='data_lancamento',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a transação ocorreu de fato', null=True),
        ),
    ]
