# Generated by Django 6.0.5 on 2026-06-11 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_membros', '0012_acaodisciplinar_avaliacaomembro_ocorrencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('tipo', models.CharField(choices=[('Visitante', 'Visitante'), ('Novo Convertido', 'Novo Convertido')], default='Visitante', max_length=50, verbose_name='Tipo')),
                ('em_acompanhamento', models.BooleanField(default=True, help_text='Marque se a pessoa ainda está sendo acompanhada ativamente', verbose_name='Em Acompanhamento')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
                ('departamento_responsavel', models.ForeignKey(blank=True, help_text='Equipe que cuidará do acompanhamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes_atribuidos', to='gestao_membros.departamento', verbose_name='Departamento Responsável')),
            ],
            options={
                'verbose_name': 'Visitante / Novo Convertido',
                'verbose_name_plural': 'Visitantes e Novos Convertidos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='VisitaCulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_culto', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Culto/Evento')),
                ('observacoes', models.TextField(blank=True, help_text='Ex: Fez apelo, Veio com a família, etc.', null=True, verbose_name='Observações')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='visitantes.visitante', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Visita / Presença',
                'verbose_name_plural': 'Histórico de Visitas',
                'ordering': ['-data_culto'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contato', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora do Contato')),
                ('meio_contato', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Ligação', 'Ligação'), ('Presencial', 'Presencial (No Culto)'), ('Visita', 'Visita no Lar'), ('Outro', 'Outro')], default='WhatsApp', max_length=50, verbose_name='Meio de Contato')),
                ('resumo_conversa', models.TextField(help_text='O que foi conversado? Como a pessoa está?', verbose_name='Resumo da Conversa')),
                ('proximo_passo', models.CharField(blank=True, help_text='Ex: Ligar na próxima semana, convidou para GC, etc.', max_length=255, null=True, verbose_name='Próximo Passo')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Líder/Voluntário Responsável')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acompanhamento', to='visitantes.visitante', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Registro de Acompanhamento',
                'verbose_name_plural': 'Diário de Acompanhamentos',
                'ordering': ['-data_contato'],
            },
        ),
    ]
