# Generated by Django 6.0.5 on 2026-06-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitaculto',
            name='modalidade',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Live', 'Online / Live')], default='Presencial', max_length=50, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='visitaculto',
            name='nome_culto',
            field=models.CharField(default='Culto da Família', max_length=255, verbose_name='Qual Culto/Evento'),
        ),
    ]
