# Generated by Django 6.0.5 on 2026-06-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_visitaculto_modalidade_visitaculto_nome_culto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='departamento_responsavel',
        ),
        migrations.AddField(
            model_name='visitante',
            name='familiar_vinculado',
            field=models.ForeignKey(blank=True, help_text='Selecione caso esta pessoa pertença à mesma família de outro visitante cadastrado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_familia', to='visitantes.visitante', verbose_name='Familiar / Relacionamento'),
        ),
    ]
