# Generated by Django 6.0.5 on 2026-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0003_remove_visitante_departamento_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='tornou_se_membro',
            field=models.BooleanField(default=False, help_text='Marque se este visitante se tornou membro integrado da igreja', verbose_name='Tornou-se Membro'),
        ),
    ]
