# Generated by Django 6.0.5 on 2026-06-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0004_visitante_tornou_se_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='desistiu',
            field=models.BooleanField(default=False, help_text='Marque se o visitante desistiu e não frequenta mais', verbose_name='Desistiu'),
        ),
    ]
