# Generated by Django 6.0.5 on 2026-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0005_visitante_desistiu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaculto',
            name='nome_culto',
            field=models.CharField(max_length=255, verbose_name='Qual Culto/Evento'),
        ),
    ]
