# Generated by Django 6.0.5 on 2026-06-16 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Completo')),
                ('estado_civil', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Outro', 'Outro')], default='Solteiro(a)', max_length=50, verbose_name='Estado Civil')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('anotacoes_gerais', models.TextField(blank=True, help_text='Informações gerais, não usar para histórico pastoral.', null=True, verbose_name='Anotações Gerais')),
                ('tags_risco', models.JSONField(blank=True, default=list, help_text='Ex: ["Risco de Suicídio", "Divórcio", "Violência"]', verbose_name='Tags de Risco')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pessoa (Atendimento)',
                'verbose_name_plural': 'Pessoas (Atendimento)',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(verbose_name='Data do Atendimento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('local', models.CharField(choices=[('Gabinete Igreja', 'Gabinete Igreja'), ('Casa da Pessoa', 'Casa da Pessoa'), ('Online (Meet/Zoom)', 'Online (Meet/Zoom)'), ('Outro', 'Outro')], default='Gabinete Igreja', max_length=50, verbose_name='Local')),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado'), ('Faltou', 'Faltou')], default='Agendado', max_length=30, verbose_name='Status')),
                ('notificacao_enviada', models.BooleanField(default=False, verbose_name='Notificação Enviada?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_pastorais', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='atendimento_pastoral.pessoaatendimento')),
            ],
            options={
                'verbose_name': 'Agendamento Pastoral',
                'verbose_name_plural': 'Agendamentos Pastorais',
                'ordering': ['data_agendamento', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SessaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sessao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Sessão')),
                ('resumo_sessao', models.TextField(verbose_name='Resumo / Prontuário')),
                ('nivel_crise', models.IntegerField(default=1, help_text='1: Saudável, 5: Alerta Máximo', verbose_name='Nível de Crise')),
                ('exige_retorno_em_dias', models.IntegerField(blank=True, help_text='Ex: 15. Deixe em branco se não precisar.', null=True, verbose_name='Sugerir Retorno em (Dias)')),
                ('is_restrito', models.BooleanField(default=True, help_text='Se marcado, nem o super admin deve ver o conteúdo (se a regra exigir).', verbose_name='Acesso Estrito ao Pastor')),
                ('agendamento', models.OneToOneField(blank=True, help_text='Opcional. Permite registrar atendimento surpresa/sem agenda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessao_realizada', to='atendimento_pastoral.agendamentopastoral')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_ministradas', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_sessoes', to='atendimento_pastoral.pessoaatendimento')),
            ],
            options={
                'verbose_name': 'Sessão de Atendimento',
                'verbose_name_plural': 'Sessões de Atendimento',
                'ordering': ['-data_sessao'],
            },
        ),
    ]
