# Generated by Django 6.0.5 on 2026-06-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento_pastoral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoatendimento',
            name='analise_comportamental',
            field=models.TextField(blank=True, help_text='Gerada automaticamente pela IA (Gemini) atuando como Psicólogo Sênior.', null=True, verbose_name='Análise Comportamental Inteligente (ACI)'),
        ),
    ]
