# Generated by Django 6.0.5 on 2026-06-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento_pastoral', '0002_sessaoatendimento_analise_comportamental'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaatendimento',
            name='nivel_crise',
            field=models.IntegerField(default=1, help_text='1: Saudável, 5: Alerta Máximo', verbose_name='Nível de Crise'),
        ),
    ]
