# Generated by Django 6.0.5 on 2026-06-15 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao_membros', '0013_departamento_is_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome de exibição. Ex: Tesouraria', max_length=100)),
                ('slug', models.SlugField(help_text='Código identificador único. Ex: tesouraria', unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone_lucide', models.CharField(default='box', help_text='Ícone Lucide para a UI', max_length=50)),
            ],
            options={
                'verbose_name': 'Módulo do Sistema',
                'verbose_name_plural': 'Módulos do Sistema',
            },
        ),
        migrations.CreateModel(
            name='PermissaoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_ver', models.BooleanField(default=False)),
                ('pode_editar', models.BooleanField(default=False)),
                ('pode_excluir', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_modulos', to='gestao_membros.departamento')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos_permitidos', to='permissoes.modulosistema')),
            ],
            options={
                'verbose_name': 'Permissão de Departamento',
                'verbose_name_plural': 'Permissões de Departamentos',
                'unique_together': {('departamento', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='PermissaoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_ver', models.BooleanField(default=False)),
                ('pode_editar', models.BooleanField(default=False)),
                ('pode_excluir', models.BooleanField(default=False)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_modulos', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_permitidos', to='permissoes.modulosistema')),
            ],
            options={
                'verbose_name': 'Permissão de Membro',
                'verbose_name_plural': 'Permissões de Membros',
                'unique_together': {('membro', 'modulo')},
            },
        ),
    ]
