# Generated by Django 6.0.5 on 2026-06-16 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permissaodepartamento',
            name='acoes_extras',
            field=models.JSONField(blank=True, default=dict, help_text='Dicionário JSON de ações customizadas'),
        ),
        migrations.AddField(
            model_name='permissaodepartamento',
            name='concedido_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='permissaodepartamento',
            name='concedido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissaodepartamento',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, help_text='Se preenchido, o acesso será revogado após esta data', null=True),
        ),
        migrations.AddField(
            model_name='permissaodepartamento',
            name='escopo_acesso',
            field=models.CharField(choices=[('global', 'Global (Toda a Igreja)'), ('departamento', 'Departamento (Apenas seu depto)'), ('proprio', 'Próprio (Apenas dados próprios)')], default='global', max_length=20),
        ),
        migrations.AddField(
            model_name='permissaomembro',
            name='acoes_extras',
            field=models.JSONField(blank=True, default=dict, help_text='Dicionário JSON de ações customizadas'),
        ),
        migrations.AddField(
            model_name='permissaomembro',
            name='concedido_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='permissaomembro',
            name='concedido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissaomembro',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, help_text='Se preenchido, o acesso será revogado após esta data', null=True),
        ),
        migrations.AddField(
            model_name='permissaomembro',
            name='escopo_acesso',
            field=models.CharField(choices=[('global', 'Global (Toda a Igreja)'), ('departamento', 'Departamento (Apenas seu depto)'), ('proprio', 'Próprio (Apenas dados próprios)')], default='global', max_length=20),
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='perfis_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
            },
        ),
        migrations.CreateModel(
            name='PermissaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_ver', models.BooleanField(default=False)),
                ('pode_editar', models.BooleanField(default=False)),
                ('pode_excluir', models.BooleanField(default=False)),
                ('acoes_extras', models.JSONField(blank=True, default=dict, help_text='Dicionário JSON de ações customizadas')),
                ('data_expiracao', models.DateTimeField(blank=True, help_text='Se preenchido, o acesso será revogado após esta data', null=True)),
                ('escopo_acesso', models.CharField(choices=[('global', 'Global (Toda a Igreja)'), ('departamento', 'Departamento (Apenas seu depto)'), ('proprio', 'Próprio (Apenas dados próprios)')], default='global', max_length=20)),
                ('concedido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissoes.modulosistema')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_modulos', to='permissoes.perfilacesso')),
            ],
            options={
                'verbose_name': 'Permissão de Perfil',
                'verbose_name_plural': 'Permissões de Perfis',
                'unique_together': {('perfil', 'modulo')},
            },
        ),
    ]
