# Generated by Django 6.0.5 on 2026-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissoes', '0002_permissaodepartamento_acoes_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissaodepartamento',
            name='pode_ver_menu',
            field=models.BooleanField(default=False, help_text='Se marcado, o menu lateral deste módulo será visível'),
        ),
        migrations.AddField(
            model_name='permissaomembro',
            name='pode_ver_menu',
            field=models.BooleanField(default=False, help_text='Se marcado, o menu lateral deste módulo será visível'),
        ),
        migrations.AddField(
            model_name='permissaoperfil',
            name='pode_ver_menu',
            field=models.BooleanField(default=False, help_text='Se marcado, o menu lateral deste módulo será visível'),
        ),
    ]
