# Generated by Django 6.0.5 on 2026-06-01 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaopdv',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdv_lider_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracaopdv',
            name='operadores',
            field=models.ManyToManyField(blank=True, related_name='pdv_operadores_config', to=settings.AUTH_USER_MODEL),
        ),
    ]
