# Generated by Django 6.0.5 on 2026-06-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_configuracaopdv_lider_configuracaopdv_operadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pin', models.CharField(help_text='Senha de 4 dígitos para login no Caixa', max_length=4)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Operadores de Caixa',
            },
        ),
        migrations.AlterField(
            model_name='caixa',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdv.operadorcaixa'),
        ),
    ]
