# Generated by Django 6.0.5 on 2026-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_operadorcaixa_alter_caixa_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nome_cliente_reserva',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='status_entrega',
            field=models.CharField(choices=[('entregue', 'Entregue'), ('retirar', 'A Retirar')], default='entregue', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='status_pagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pago', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('imediata', 'Pronta Entrega'), ('reserva', 'Reserva')], default='imediata', max_length=20),
        ),
    ]
