# Generated by Django 6.0.5 on 2026-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0004_venda_nome_cliente_reserva_venda_status_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='CBS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ibs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IBS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imposto_seletivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Imposto Seletivo (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(default='00000000', max_length=20),
        ),
    ]
