# Generated by Django 6.0.5 on 2026-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_produto_cbs_produto_ibs_produto_imposto_seletivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tem_preparo',
            field=models.BooleanField(default=False, verbose_name='Requer Preparo na Cozinha?'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(default='Dinheiro', max_length=255),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status_entrega',
            field=models.CharField(choices=[('preparo', 'Em Preparo'), ('retirar', 'A Retirar'), ('entregue', 'Entregue')], default='entregue', max_length=20),
        ),
    ]
