# Generated by Django 6.0.5 on 2026-05-25 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico_fixo', models.CharField(help_text='Ex: PRT-001', max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('grupo', 'Grupo'), ('setor', 'Setor'), ('ministerio', 'Ministério'), ('departamento', 'Departamento')], max_length=20)),
                ('habilidades_requeridas', models.JSONField(blank=True, default=dict)),
                ('lideres', models.ManyToManyField(blank=True, related_name='departamentos_liderados', to=settings.AUTH_USER_MODEL)),
                ('membros_ativos', models.ManyToManyField(blank=True, related_name='departamentos_ativos', to=settings.AUTH_USER_MODEL)),
                ('sub_lideres', models.ManyToManyField(blank=True, related_name='departamentos_subliderados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
