# Generated by Django 6.0.5 on 2026-05-25 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.CharField(help_text='Ex: Viagem, Doença, Trabalho', max_length=200)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
