# Generated by Django 6.0.5 on 2026-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0003_avisomural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id_unico_fixo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
