# Generated by Django 6.0.5 on 2026-05-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0005_habilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='habilidades_requeridas',
        ),
        migrations.AddField(
            model_name='departamento',
            name='requisitos_habilidades',
            field=models.ManyToManyField(blank=True, related_name='departamentos_requerentes', to='gestao_membros.habilidade'),
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='gestao_membros.departamento')),
                ('requisitos', models.ManyToManyField(blank=True, to='gestao_membros.habilidade')),
            ],
        ),
    ]
