# Generated by Django 6.0.5 on 2026-05-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0006_remove_departamento_habilidades_requeridas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/logos/'),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='gestao_membros.departamento'),
        ),
        migrations.AlterField(
            model_name='habilidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
