# Generated by Django 6.0.5 on 2026-05-27 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0007_departamento_logo_habilidade_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='departamentos/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
