# Generated by Django 6.0.5 on 2026-05-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0008_alter_departamento_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='requisitos_habilidades',
        ),
        migrations.CreateModel(
            name='ConfiguracaoSlotEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('segunda_oracao', 'Segunda: Culto de Oração (20:00 - 21:00)'), ('quarta_profetica', 'Quarta: Quarta Profética (20:00 - 22:00)'), ('quinta_saber', 'Quinta: Quinta do Saber (19:30 - 20:30)'), ('domingo_manha', 'Domingo da Família: Manhã (09:30 - 11:30)'), ('domingo_noite', 'Domingo da Família: Noite (19:30 - 21:30)'), ('eventos', 'Eventos Extraordinários')], max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_slots', to='gestao_membros.departamento')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_membros.funcao')),
            ],
            options={
                'unique_together': {('departamento', 'tipo_evento', 'funcao')},
            },
        ),
    ]
