# Generated by Django 6.0.5 on 2026-05-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0009_remove_departamento_requisitos_habilidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisomural',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avisomural',
            name='link_externo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='AvisoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='avisos_anexos/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='gestao_membros.avisomural')),
            ],
        ),
    ]
