# Generated by Django 6.0.5 on 2026-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0010_avisomural_data_expiracao_avisomural_link_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoslotescala',
            name='tipo_evento',
            field=models.CharField(max_length=50),
        ),
    ]
