# Generated by Django 6.0.5 on 2026-06-01 19:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0011_alter_configuracaoslotescala_tipo_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoDisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('advertencia', 'Advertência Formal'), ('suspensao', 'Suspensão'), ('expulsao', 'Desligamento / Expulsão')], max_length=20)),
                ('motivo', models.TextField()),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('data_fim_suspensao', models.DateField(blank=True, null=True)),
                ('enviado_email', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_disciplinares_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_disciplinares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentarios', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('enviado_ao_membro', models.BooleanField(default=False)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_ocorrencia', models.DateField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='ocorrencias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('envolvidos', models.ManyToManyField(related_name='ocorrencias_envolvido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
