# Generated by Django 6.0.5 on 2026-06-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0012_acaodisciplinar_avaliacaomembro_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Departamentos do sistema não podem ser excluídos e garantem o funcionamento de módulos cruciais.'),
        ),
    ]
