# Generated by Django 6.0.5 on 2026-06-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0015_anotacaorh'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='instrucoes_padrao_escala',
            field=models.TextField(blank=True, help_text='Instruções padrão que aparecerão no rodapé do PDF das escalas.'),
        ),
    ]
