# Generated by Django 6.0.5 on 2026-06-24 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0016_departamento_instrucoes_padrao_escala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funcao',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='funcoes_associadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
