# Generated by Django 6.0.5 on 2026-06-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_membro_habilidades'),
        ('gestao_membros', '0017_funcao_membros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcao',
            name='requisitos',
        ),
        migrations.DeleteModel(
            name='Habilidade',
        ),
    ]
