# Generated by Django 6.0.5 on 2026-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_membros', '0018_remove_funcao_requisitos_delete_habilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id_unico_fixo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
